function Get-SiteObjects {
    Param(
        [object]$EPSAPI
    )
    Begin {
        $oEPSAPI = if ($EPSAPI) { $EPSAPI } else { $Global:EPSAPI }
        $sOperationName = "getSiteObjects"
        $sQuery = "query getSiteObjects {
            getSiteObjects {
              uid
              type
              name
              comments
              host
              __typename
            }
          }
          "
        $hVariables = @{}
    }
    Process {
        $oAPIResult = $oEPSAPI.CallAPI($sOperationName, $sQuery, $hVariables)
        return $oAPIResult.data.getSiteObjects
    }
}